services:
  db:
    image: postgres:17-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: gembala
      POSTGRES_PASSWORD: gembala
      POSTGRES_DB: gembala
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
